python run_infer.py \
--model_path ../pretrained/pecan-hover-net-pytorch.tar \
--gpu '0,1' \
--model_mode 'pannuke' \
--run_mode 'tile' \
--nr_types 6 \
--nr_inference_workers 8 \
--nr_post_proc_workers 16 \
--batch_size 64 \
--input_dir dataset/sample_tiles/imgs/ \
--output_dir dataset/sample_tiles/pred/ \
--patch_input_shape 256 \
--patch_output_shape 164 
